/* SPDX-License-Identifier: MIT OR Apache-2.0 */

#ifndef ARCANE_SDK_H
#define ARCANE_SDK_H

#pragma once

/* Generated by cbindgen from src/ffi.rs — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Force offline ownership check. Returns 0 on success, 1 on bad args, 2 on SdkError.
//
// `game_id` must be a valid NUL-terminated UTF-8 C string (portal public key).
int arcane_check_ownership_offline(const char *game_id, char *err_buf, size_t err_len);

// Default launch check (portal public key). Returns 0 on success, 1 on bad args, 2 on SdkError.
//
// `game_id` must be a valid NUL-terminated UTF-8 C string (portal public key).
int arcane_sdk_init(const char *game_id, char *err_buf, size_t err_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARCANE_SDK_H */
