/* SPDX-License-Identifier: MIT OR Apache-2.0 */

#ifndef ARCANE_SDK_H
#define ARCANE_SDK_H

#pragma once

/* Generated by cbindgen from src/ffi.rs — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Action return codes.
#define ARCANE_OK 0

#define ARCANE_ERR_ARGUMENT 1

#define ARCANE_ERR_SDK 2

// Getter return codes (negative).
#define ARCANE_ERR_NOT_INITIALIZED -1

#define ARCANE_ERR_BAD_BUFFER -2

#define ARCANE_ERR_BUFFER_TOO_SMALL -3

#define ARCANE_ERR_UNAVAILABLE -4

// `arcane_sdk_ownership` results.
#define ARCANE_OWNERSHIP_OWNED 0

#define ARCANE_OWNERSHIP_DRM_DISABLED 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Unix timestamp of the last successful check, or -1 when not initialised.
long long arcane_sdk_checked_at(void);

// Write this machine's device fingerprint into `buf`.
//
// # Safety
//
// `buf` must be null or point to at least `len` writable bytes.
int arcane_sdk_device_hash(char *buf, size_t len);

// Count one rendered frame, for FPS sampling. Call once per frame.
//
// Outside a sampling window this is a relaxed atomic load; inside one it adds a
// relaxed increment. Does nothing before `arcane_sdk_init` succeeds.
void arcane_sdk_frame(void);

// Write the canonical title id into `buf`.
//
// # Safety
//
// `buf` must be null or point to at least `len` writable bytes.
int arcane_sdk_game_id(char *buf, size_t len);

// Verify ownership and build the process-wide client. Call once at launch.
//
// `public_key` must be a NUL-terminated UTF-8 string — the public key generated
// for this title in the Arcane portal.
//
// Returns 0 on success, 1 if `public_key` is null or not UTF-8, 2 on an SDK
// error written to `err_buf` as `"code: message"`.
//
// # Safety
//
// `public_key` must be a valid NUL-terminated C string. `err_buf` must be null
// or point to at least `err_len` writable bytes.
int arcane_sdk_init(const char *public_key, char *err_buf, size_t err_len);

// Whether a client is currently initialised. Returns 1 or 0.
int arcane_sdk_is_initialized(void);

// Write the last error as JSON into `buf`:
// `{"code","message","hint","retryable","context"}`.
//
// Returns -4 when no error has been recorded since the last success.
//
// # Safety
//
// `buf` must be null or point to at least `len` writable bytes.
int arcane_sdk_last_error_json(char *buf, size_t len);

// Ownership as of the last check.
//
// Returns 0 (owned), 1 (DRM disabled for this title), or -1 if not initialised.
int arcane_sdk_ownership(void);

// Write the public key this client was initialised with into `buf`.
//
// # Safety
//
// `buf` must be null or point to at least `len` writable bytes.
int arcane_sdk_public_key(char *buf, size_t len);

// Re-run the ownership check against Arcane desktop and update the client.
//
// Returns 0 on success, 1 if the client is not initialised, 2 on an SDK error.
// On failure the client keeps its previous state.
//
// # Safety
//
// `err_buf` must be null or point to at least `err_len` writable bytes.
int arcane_sdk_refresh(char *err_buf, size_t err_len);

// Write the play session state as JSON into `buf`:
// `{"session_id","tracking","played_seconds","fps_sampling","samples_taken","last_fps_avg"}`.
//
// `tracking` is `"active"`, `"pending"` or `"disabled"`. 256 bytes is enough.
//
// # Safety
//
// `buf` must be null or point to at least `len` writable bytes.
int arcane_sdk_session_json(char *buf, size_t len);

// Record the current display settings, attached to the FPS samples that follow.
//
// Both strings are NUL-terminated UTF-8, for example `"2560x1440"` and
// `"high"`. Empty strings clear the values. Never call this from the render
// loop — it takes a short lock.
//
// Returns 0 on success, 1 on a null / non-UTF-8 argument or when the client is
// not initialised.
//
// # Safety
//
// `resolution` and `preset` must be valid NUL-terminated C strings.
int arcane_sdk_set_graphics(const char *resolution, const char *preset);

// End the play session and drop the client.
//
// Reports the final playtime to the Arcane desktop app with a 2-second timeout,
// then releases the singleton. Call it when the game exits; it is also what you
// want on an editor play-mode reload.
void arcane_sdk_shutdown(void);

// Unix timestamp of the ownership ticket's expiry, or -1 when unknown.
long long arcane_sdk_ticket_expires_at(void);

// Write the signed-in Arcane account id into `buf`.
//
// # Safety
//
// `buf` must be null or point to at least `len` writable bytes.
int arcane_sdk_user_id(char *buf, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARCANE_SDK_H */
